### PR TITLE
Fix missing "url"

### PR DESCRIPTION
**Pull request by takke**
Fix missing "url" param on DM user object

### CODE REVIEW

**Comment by rowanseymour** [comment]
What's the timeframe for a release with this fix? Thanks

**Comment by sudpaw** [comment]
@takke @yusuke Could you release this fix please? It is affecting us a great deal!

Thx!

**Comment by Mads-Andersen** [comment]
Same here.

**Comment by yusuke** [comment]
Hi,

Basically it’s an API side issue, but thanks to @takke, we introduced a workaround for it.
Please try version 4.0.5 available on the maven central repo.

Best regards,
-- 
Yusuke Yamamoto
@yusukey
http://samuraism.com/

**Comment by rowanseymour** [comment]
@yusuke thanks for the quick turnaround on this release. I hope the Twitter devs know how much pain they caused API users yesterday :)

**Comment by sudpaw** [comment]
thx!

**Pull request merged**
