### PR TITLE
add video support to media entity

### PR DESCRIPTION
**Pull request by takke**
see https://twittercommunity.com/t/twitter-video-support-in-rest-and-streaming-api/31258
see https://twittercommunity.com/t/adding-animated-gifs-via-rest-and-streaming-apis/30070

### CODE REVIEW

**Comment by zorrobiwan** [comment]
Hi @yusuke , do you know when this feature will be pulled and when you'll be able to create a new release of Twitter4J ? I'm testing the video support and it's working well (as far as I made my tests) and I would like to use it "officially" (I mean, once packed in your library). Thx !

**Comment by matthewbogner** [comment]
I am also interested in this code being merged and a new release of twitter4j.  Thanks!

**Comment by phuc77** [comment]
I'm also eagerly awaiting for this feature, thanks in advance!

**Comment by marz619** [comment]
Hi, I know it's been mentioned already, but I am also interested in having this feature available in the core library. Thanks!

**Comment by yusuke** [comment]
LGTM!

**Pull request merged**
