### PR TITLE
Added getIdString() method to Status.

### PR DESCRIPTION
**Pull request by fredriko**
Added a method for getting the id_str field from a Status, in accordance to the recommendations made here: https://dev.twitter.com/overview/api/twitter-ids-json-and-snowflake

### CODE REVIEW

**Comment by grantneale** [comment]
It's worth considering adding similar methods for other id fields, including:

- user.id_str
- quoted_status_id_str
- replied_to_status.id_str
- etc

**Comment by yusuke** [comment]
Those are for JavaScript.
There is no need to handle those string values in Java. Java's long type can handle those values correctly.

**Comment by grantneale** [comment]
Have you tested that? I streamed some tweets using Twitter4J yesterday, the tweet IDs were all truncated/invalid. 

If you substitute IDs into twitter.com/statuses/ID they do not load. Using the id_str

**Comment by grantneale** [comment]
from the raw Json worked though.  

I was streaming from the filter API.

**Comment by fredriko** [comment]
@grantneale that's the behavior I experienced as well. However, I cannot reproduce the error right now.

**Comment by aadawi** [comment]
we have to get str value for all ids checks below response from twitter most of long values for ids not valid:
{
"created_at": "Mon Jul 24 01:59:25 +0000 2017",
"id": **889303978709729300**,
"id_str": "**889303978709729280**",
"text": "RT @pumakorea: 우리가 준비한 작은 정성이\n너희를 웃게 할 수 있으면 좋겠어.\n\nmade by BTS\n\nBTS 팬사인회 이벤트 자세히 보기> https://t.co/ts2gixlojg https://t.co/6JlD75IGf1",
"source": "<a href="http://twitter.com\" rel="nofollow">Twitter Web Client",
"truncated": false,
"in_reply_to_status_id": null,
"in_reply_to_status_id_str": null,
"in_reply_to_user_id": null,
"in_reply_to_user_id_str": null,
"in_reply_to_screen_name": null,
"user": {
"id": 4889151085,
"id_str": "4889151085",
"name": ":lollipop:ลูกกวาดเสียบไม้:lollipop:",
"screen_name": "OmyimPoP",
"location": "อ.บางใหญ่, จ.นนทบุรี",
"url": "http://lollipopservicescene.blogspot.com/",
"description": "♡BTS FANCLUB♡ไรท์อมยิ้มเอง☆นักเขียนมือใหม่☆♡เข้ามาทักทายกันได้น่ะ♡ตอบกลับทุกข้อความนะแต่อาจช้าหน่อย☆#ไรท์เตอร์ที่รัก☆#Kissจิน☆",
"protected": false,
"verified": false,
"followers_count": 265,
"friends_count": 102,
"listed_count": 0,
"favourites_count": 7605,
"statuses_count": 2892,
"created_at": "Wed Feb 10 18:25:08 +0000 2016",
"utc_offset": -25200,
"time_zone": "Pacific Time (US & Canada)",
"geo_enabled": false,
"lang": "th",
"contributors_enabled": false,
"is_translator": false,
"profile_background_color": "000000",
"profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
"profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
"profile_background_tile": false,
"profile_link_color": "F58EA8",
"profile_sidebar_border_color": "000000",
"profile_sidebar_fill_color": "000000",
"profile_text_color": "000000",
"profile_use_background_image": false,
"profile_image_url": "http://pbs.twimg.com/profile_images/789022029081026562/sIUx_YXX_normal.jpg",
"profile_image_url_https": "https://pbs.twimg.com/profile_images/789022029081026562/sIUx_YXX_normal.jpg",
"profile_banner_url": "https://pbs.twimg.com/profile_banners/4889151085/1496812354",
"default_profile": false,
"default_profile_image": false,
"following": null,
"follow_request_sent": null,
"notifications": null
},
"geo": null,
"coordinates": null,
"place": null,
"contributors": null,
"retweeted_status": {
"created_at": "Fri Jul 21 03:31:44 +0000 2017",
"id": **888240044917399600**,
"id_str": "**888240044917399552**",
"text": "우리가 준비한 작은 정성이\n너희를 웃게 할 수 있으면 좋겠어.\n\nmade by BTS\n\nBTS 팬사인회 이벤트 자세히 보기> https://t.co/ts2gixlojg https://t.co/6JlD75IGf1",
"display_text_range": [
0,
97
],
"source": "<a href="http://twitter.com\" rel="nofollow">Twitter Web Client",
"truncated": false,
"in_reply_to_status_id": null,
"in_reply_to_status_id_str": null,
"in_reply_to_user_id": null,
"in_reply_to_user_id_str": null,
"in_reply_to_screen_name": null,
"user": {
"id": 134661364,
"id_str": "134661364",
"name": "푸마코리아 PUMA Korea",
"screen_name": "pumakorea",
"location": "Seoul, Korea",
"url": "http://www.instagram.com/puma_kr",
"description": "made by BTS",
"protected": false,
"verified": false,
"followers_count": 95081,
"friends_count": 0,
"listed_count": 506,
"favourites_count": 0,
"statuses_count": 5285,
"created_at": "Mon Apr 19 03:00:10 +0000 2010",
"utc_offset": 32400,
"time_zone": "Seoul",
"geo_enabled": false,
"lang": "en",
"contributors_enabled": false,
"is_translator": false,
"profile_background_color": "EBEBEB",
"profile_background_image_url": "http://pbs.twimg.com/profile_background_images/497265495444185088/7fPJ3CIu.jpeg",
"profile_background_image_url_https": "https://pbs.twimg.com/profile_background_images/497265495444185088/7fPJ3CIu.jpeg",
"profile_background_tile": false,
"profile_link_color": "000000",
"profile_sidebar_border_color": "FFFFFF",
"profile_sidebar_fill_color": "FAFAFA",
"profile_text_color": "050505",
"profile_use_background_image": true,
"profile_image_url": "http://pbs.twimg.com/profile_images/813561321509638144/DYg0oXGe_normal.jpg",
"profile_image_url_https": "https://pbs.twimg.com/profile_images/813561321509638144/DYg0oXGe_normal.jpg",
"profile_banner_url": "https://pbs.twimg.com/profile_banners/134661364/1500282187",
"default_profile": false,
"default_profile_image": false,
"following": null,
"follow_request_sent": null,
"notifications": null
},
"geo": null,
"coordinates": null,
"place": null,
"contributors": null,
"is_quote_status": false,
"retweet_count": 180090,
"favorite_count": 353226,
"entities": {
"hashtags": [],
"urls": [
{
"url": "https://t.co/ts2gixlojg",
"expanded_url": "http://www.pumablog.co.kr",
"display_url": "pumablog.co.kr",
"indices": [
74,
97
]
}
],
"user_mentions": [],
"symbols": [],
"media": [
{
"id": **888235483230224400**,
"id_str": "**888235483230224384**",
"indices": [
98,
121
],
"media_url": "http://pbs.twimg.com/ext_tw_video_thumb/888235483230224384/pu/img/XsWKvYVK27q2kb19.jpg",
"media_url_https": "https://pbs.twimg.com/ext_tw_video_thumb/888235483230224384/pu/img/XsWKvYVK27q2kb19.jpg",
"url": "https://t.co/6JlD75IGf1",
"display_url": "pic.twitter.com/6JlD75IGf1",
"expanded_url": "https://twitter.com/pumakorea/status/888240044917399552/video/1",
"type": "photo",
"sizes": {
"thumb": {
"w": 150,
"h": 150,
"resize": "crop"
},
"medium": {
"w": 600,
"h": 338,
"resize": "fit"
},
"small": {
"w": 340,
"h": 191,
"resize": "fit"
},
"large": {
"w": 1024,
"h": 576,
"resize": "fit"
}
}
}
]
},
"extended_entities": {
"media": [
{
"id": **888235483230224400**,
"id_str": "**888235483230224384**",
"indices": [
98,
121
],
"media_url": "http://pbs.twimg.com/ext_tw_video_thumb/888235483230224384/pu/img/XsWKvYVK27q2kb19.jpg",
"media_url_https": "https://pbs.twimg.com/ext_tw_video_thumb/888235483230224384/pu/img/XsWKvYVK27q2kb19.jpg",
"url": "https://t.co/6JlD75IGf1",
"display_url": "pic.twitter.com/6JlD75IGf1",
"expanded_url": "https://twitter.com/pumakorea/status/888240044917399552/video/1",
"type": "video",
"sizes": {
"thumb": {
"w": 150,
"h": 150,
"resize": "crop"
},
"medium": {
"w": 600,
"h": 338,
"resize": "fit"
},
"small": {
"w": 340,
"h": 191,
"resize": "fit"
},
"large": {
"w": 1024,
"h": 576,
"resize": "fit"
}
},
"video_info": {
"aspect_ratio": [
16,
9
],
"duration_millis": 94094,
"variants": [
{
"bitrate": 832000,
"content_type": "video/mp4",
"url": "https://video.twimg.com/ext_tw_video/888235483230224384/pu/vid/640x360/qbT06B4y6LqfZjWU.mp4"
},
{
"content_type": "application/x-mpegURL",
"url": "https://video.twimg.com/ext_tw_video/888235483230224384/pu/pl/knnYRlg1AeeCyj1b.m3u8"
},
{
"bitrate": 320000,
"content_type": "video/mp4",
"url": "https://video.twimg.com/ext_tw_video/888235483230224384/pu/vid/320x180/ruEzl5FkjAl3JevR.mp4"
},
{
"bitrate": 2176000,
"content_type": "video/mp4",
"url": "https://video.twimg.com/ext_tw_video/888235483230224384/pu/vid/1280x720/CBqXjXRzTxBtvkMV.mp4"
}
]
}
}
]
},
"favorited": false,
"retweeted": false,
"possibly_sensitive": false,
"filter_level": "low",
"lang": "ko"
},
"is_quote_status": false,
"retweet_count": 0,
"favorite_count": 0,
"entities": {
"hashtags": [],
"urls": [
{
"url": "https://t.co/ts2gixlojg",
"expanded_url": "http://www.pumablog.co.kr",
"display_url": "pumablog.co.kr",
"indices": [
89,
112
]
}
],
"user_mentions": [
{
"screen_name": "pumakorea",
"name": "푸마코리아 PUMA Korea",
"id": 134661364,
"id_str": "134661364",
"indices": [
3,
13
]
}
],
"symbols": [],
"media": [
{
"id": 888235483230224400,
"id_str": "888235483230224384",
"indices": [
113,
136
],
"media_url": "http://pbs.twimg.com/ext_tw_video_thumb/888235483230224384/pu/img/XsWKvYVK27q2kb19.jpg",
"media_url_https": "https://pbs.twimg.com/ext_tw_video_thumb/888235483230224384/pu/img/XsWKvYVK27q2kb19.jpg",
"url": "https://t.co/6JlD75IGf1",
"display_url": "pic.twitter.com/6JlD75IGf1",
"expanded_url": "https://twitter.com/pumakorea/status/888240044917399552/video/1",
"type": "photo",
"sizes": {
"thumb": {
"w": 150,
"h": 150,
"resize": "crop"
},
"medium": {
"w": 600,
"h": 338,
"resize": "fit"
},
"small": {
"w": 340,
"h": 191,
"resize": "fit"
},
"large": {
"w": 1024,
"h": 576,
"resize": "fit"
}
},
"source_status_id": **888240044917399600**,
"source_status_id_str": "**888240044917399552**",
"source_user_id": 134661364,
"source_user_id_str": "134661364"
}
]
},
"extended_entities": {
"media": [
{
"id": 888235483230224400,
"id_str": "888235483230224384",
"indices": [
113,
136
],
"media_url": "http://pbs.twimg.com/ext_tw_video_thumb/888235483230224384/pu/img/XsWKvYVK27q2kb19.jpg",
"media_url_https": "https://pbs.twimg.com/ext_tw_video_thumb/888235483230224384/pu/img/XsWKvYVK27q2kb19.jpg",
"url": "https://t.co/6JlD75IGf1",
"display_url": "pic.twitter.com/6JlD75IGf1",
"expanded_url": "https://twitter.com/pumakorea/status/888240044917399552/video/1",
"type": "video",
"sizes": {
"thumb": {
"w": 150,
"h": 150,
"resize": "crop"
},
"medium": {
"w": 600,
"h": 338,
"resize": "fit"
},
"small": {
"w": 340,
"h": 191,
"resize": "fit"
},
"large": {
"w": 1024,
"h": 576,
"resize": "fit"
}
},
"source_status_id": 888240044917399600,
"source_status_id_str": "888240044917399552",
"source_user_id": 134661364,
"source_user_id_str": "134661364",
"video_info": {
"aspect_ratio": [
16,
9
],
"duration_millis": 94094,
"variants": [
{
"bitrate": 832000,
"content_type": "video/mp4",
"url": "https://video.twimg.com/ext_tw_video/888235483230224384/pu/vid/640x360/qbT06B4y6LqfZjWU.mp4"
},
{
"content_type": "application/x-mpegURL",
"url": "https://video.twimg.com/ext_tw_video/888235483230224384/pu/pl/knnYRlg1AeeCyj1b.m3u8"
},
{
"bitrate": 320000,
"content_type": "video/mp4",
"url": "https://video.twimg.com/ext_tw_video/888235483230224384/pu/vid/320x180/ruEzl5FkjAl3JevR.mp4"
},
{
"bitrate": 2176000,
"content_type": "video/mp4",
"url": "https://video.twimg.com/ext_tw_video/888235483230224384/pu/vid/1280x720/CBqXjXRzTxBtvkMV.mp4"
}
]
}
}
]
},
"favorited": false,all long ids not valid if the id value is more than 
"retweeted": false,
"possibly_sensitive": false,
"filter_level": "low",
"lang": "ko",
"timestamp_ms": "1500861565650"
},

**Comment by grantneale** [comment]
> There is no need to handle those string values in Java. Java's long type can handle those values correctly.

There is definitely a need to handle those String values in Java. Java's long type is for 64-bit signed values, but does handle 64-bit unsigned values correctly. (Strictly this may be possible in Java SE 8 and later, but only if special care is taken).

**Pull request closed without merging**
