### PR TITLE
First version for the Twitter August 2018 changes

### PR DESCRIPTION
**Pull request by nbartels**
* old direct message handling marked as deprecated
* new direct message event handling added
* pulling single DM possible
* pulling a list of DMs possible
* paging in that list possible (please check the examples, the API changed)
* destroying a direct message added
* sending of direct message added (only simple text is supported atm)

### CODE REVIEW

**Comment by dkomputer** [comment]
Tests are failing.
I've tested new DM creating function and it's good.

**Comment by mr-mos** [comment]
@yusuke  Will there be a release for the August changes the next days? thx

**Comment by yusuke** [comment]
I had been working on fixing test cases for the last two weeks.
Now all tests are green and I'll be start merging those PRs! :)

-- 
山本 裕介
https://samuraism.jp/

**Comment by mr-mos** [comment]
Great! :)

**Comment by yusuke** [comment]
Thanks.
new DM API support is covered by #260

**Pull request closed without merging**
