### PR TITLE
Adding Chuncked support.

### PR DESCRIPTION
**Pull request by dk8996**
Adding Chuncked support that enables video upload and posting to Twitter.

Dev doc:
https://dev.twitter.com/rest/public/uploading-media#chunkedupload

### CODE REVIEW

**Comment by omry-hay-wochit** [comment]
@dk8996 - I took the code and played with it and found a problem when the video is larger then 5MB.
Since twitter allow each chunk to be [at most 5MB](https://dev.twitter.com/rest/reference/post/media/upload-chunked), your code does not handle this situation.
You need to check the size of the video and send 5MB of it each time.

**Comment by dk8996** [comment]
@omry-hay-wochit  I noticed that as well.  Thanks for letting me know

**Comment by omry-hay-wochit** [comment]
@dk8996 - Are you going to fix it anytime soon?

**Comment by dk8996** [comment]
Closing this.  See the new version #255

**Comment by chiragpurohit71085** [comment]
HI

I am not able to find code/sample for video uploading. Am I am missing anything?

**Comment by manas-xtremand** [comment]
@dk8996 Can we get a maven dependency for video upload functionality?

**Comment by dk8996** [comment]
@manas-xtremand see https://github.com/yusuke/twitter4j/pull/255/files.  Also I have my own maven repo, hosted on GitHub see: https://github.com/dk8996/maven.

**Comment by eos1d3** [comment]
@dk8996 I have been using above for a long time. Since today it does not work any more with status 403. That is: The request is understood, but it has been refused or access is not allowed. An accompanying error message will explain why. This code is used when requests are being denied due to update limits . Other reasons for this status being returned are listed alongside the response codes in the table below.

Any idea?

**Comment by dk8996** [comment]
@eos1d3 this branch is closed see #255

**Comment by eos1d3** [comment]
Yes, I know. I am using your latest maven and worked perfectly for months.
But now it always shows 403 for video. I shall be using your latest
revision, #255.

**Comment by dk8996** [comment]
@eos1d3 403 code can sometimes mean authentication problem.  Make sure your token still works.

**Comment by eos1d3** [comment]
Definitely not authentication problem. My application can still tweet any
image. Only chunked upload will fail.

I also tried another Twitter account and got the same problem for chunked
upload.

403 can also mean the video format or request data is rejected.

This problem occured after Twitter changed it 140 chars limit to 280. I
suspect Twitter may change somthing else to break the library.

PS: Your implantation does not work with gif too. The code seems to support
video/mp4 only. Really need your help to fix video problem first. Thanks.


On Oct 1, 2017 1:09 AM, "Dimitry Kudryavtsev" <notifications@github.com>
wrote:

@eos1d3 <https://github.com/eos1d3> 403 code can sometimes mean
authentication problem. Make sure your token still works.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/yusuke/twitter4j/pull/226#issuecomment-333322222>, or mute
the thread

**Comment by eos1d3** [comment]
@dk8996 Is it related to not using multipart in the post request? I see multipart is required in twitter api.
I have no idea how to do this with oauth request. If you tell me how to do, I will try to fix.

**Comment by eos1d3** [comment]
@dk8996 After around 3 days of video upload problem, the same program can upload the same video now. It looks like problem is fixed in Twitter side as both two twitter accounts can work suddenly without doing anything.

Thanks!

**Comment by dk8996** [comment]
This is close.  Please look at this PR (https://github.com/yusuke/twitter4j/pull/255)

Also a maven repo for this branch (https://github.com/dk8996/maven)

**Pull request closed without merging**
