### PR TITLE
Add idStr and inReplyStatusIdStr to get correct twitter ids

### PR DESCRIPTION
**Pull request by aadawi**
Add new fields idstr and inReplyToStatusIdStr to get correct ids values from twitter

### CODE REVIEW

**Comment by takke** [comment]
no need.

see: https://github.com/yusuke/twitter4j/pull/259

**Comment by aadawi** [comment]
@takke if you check latest responses from twitter id and id_str, not the same value cause if that we have to add id_str :), check below response from twitter:

{
    "created_at": "Mon Jul 24 02:00:19 +0000 2017",
    "id": **889304203369304000**,
    "id_str": "**889304203369304066**",
    "text": "괘조와🎶 https://t.co/gwOXYUjg8d",
    "display_text_range": [
      0,
      4
    ],
    "source": "<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>",
    "truncated": false,
    "in_reply_to_status_id": null,
    "in_reply_to_status_id_str": null,
    "in_reply_to_user_id": null,
    "in_reply_to_user_id_str": null,
    "in_reply_to_screen_name": null,
    "user": {
      "id": 858283648755290100,
      "id_str": "858283648755290112",
      "name": "권디닝💜",
      "screen_name": "101_dining",
      "location": "🐥큡즈 사랑해🐥",
      "url": null,
      "description": "🌟바른얼굴콜렉터🌟",
      "protected": false,
      "verified": false,
      "followers_count": 203,
      "friends_count": 126,
      "listed_count": 0,
      "favourites_count": 2299,
      "statuses_count": 2297,
      "created_at": "Sat Apr 29 11:35:42 +0000 2017",
      "utc_offset": null,
      "time_zone": null,
      "geo_enabled": false,
      "lang": "ko",
      "contributors_enabled": false,
      "is_translator": false,
      "profile_background_color": "F5F8FA",
      "profile_background_image_url": "",
      "profile_background_image_url_https": "",
      "profile_background_tile": false,
      "profile_link_color": "1DA1F2",
      "profile_sidebar_border_color": "C0DEED",
      "profile_sidebar_fill_color": "DDEEF6",
      "profile_text_color": "333333",
      "profile_use_background_image": true,
      "profile_image_url": "http://pbs.twimg.com/profile_images/889295159090982913/OslBuRBw_normal.jpg",
      "profile_image_url_https": "https://pbs.twimg.com/profile_images/889295159090982913/OslBuRBw_normal.jpg",
      "profile_banner_url": "https://pbs.twimg.com/profile_banners/858283648755290112/1500113673",
      "default_profile": true,
      "default_profile_image": false,
      "following": null,
      "follow_request_sent": null,
      "notifications": null
    },
    "geo": null,
    "coordinates": null,
    "place": null,
    "contributors": null,
    "is_quote_status": false,
    "retweet_count": 0,
    "favorite_count": 0,
    "entities": {
      "hashtags": [],
      "urls": [],
      "user_mentions": [],
      "symbols": [],
      "media": [
        {
          "id": **889304185283518500**,
          "id_str": "**889304185283518464**",
          "indices": [
            5,
            28
          ],
          "media_url": "http://pbs.twimg.com/media/DFdxcd0XoAAKR28.jpg",
          "media_url_https": "https://pbs.twimg.com/media/DFdxcd0XoAAKR28.jpg",
          "url": "https://t.co/gwOXYUjg8d",
          "display_url": "pic.twitter.com/gwOXYUjg8d",
          "expanded_url": "https://twitter.com/101_dining/status/889304203369304066/photo/1",
          "type": "photo",
          "sizes": {
            "thumb": {
              "w": 150,
              "h": 150,
              "resize": "crop"
            },
            "small": {
              "w": 383,
              "h": 680,
              "resize": "fit"
            },
            "large": {
              "w": 1080,
              "h": 1920,
              "resize": "fit"
            },
            "medium": {
              "w": 675,
              "h": 1200,
              "resize": "fit"
            }
          }
        }
      ]
    },
    "extended_entities": {
      "media": [
        {
          "id": 889304185283518500,
          "id_str": "889304185283518464",
          "indices": [
            5,
            28
          ],
          "media_url": "http://pbs.twimg.com/media/DFdxcd0XoAAKR28.jpg",
          "media_url_https": "https://pbs.twimg.com/media/DFdxcd0XoAAKR28.jpg",
          "url": "https://t.co/gwOXYUjg8d",
          "display_url": "pic.twitter.com/gwOXYUjg8d",
          "expanded_url": "https://twitter.com/101_dining/status/889304203369304066/photo/1",
          "type": "photo",
          "sizes": {
            "thumb": {
              "w": 150,
              "h": 150,
              "resize": "crop"
            },
            "small": {
              "w": 383,
              "h": 680,
              "resize": "fit"
            },
            "large": {
              "w": 1080,
              "h": 1920,
              "resize": "fit"
            },
            "medium": {
              "w": 675,
              "h": 1200,
              "resize": "fit"
            }
          }
        }
      ]
    },
    "favorited": false,
    "retweeted": false,
    "possibly_sensitive": false,
    "filter_level": "low",
    "lang": "ko",
    "timestamp_ms": "1500861619213"
  }

**Comment by grantneale** [comment]
> no need.

Disagree, the issue in in #259 is real, and remains unresolved.

**Comment by aadawi** [comment]
@grantneale disagree on what? 
the response from twitter returning wrong value in id element !!
and sorry but what you mean by the issue 259 is real and others are unresolved !!

**Comment by grantneale** [comment]
@aadawi, I disagree with your statement that there is no need to expose the `id_str` (and string representation of other id fields).

Furthermore, you cited PR #259 as evidence that exposing string representations of the ids is unnecessary.  The bug to which PR #259 relates is still outstanding, despite comments in that PR suggesting that the bug does not exist.

Twitter returns the correct value in the id element in their raw response.  However, the `long` value returned by Twitter4J is sometime incorrect, indicating that a bug exists in the code (or third-party dependencies) used to parse the snowflake id fields from the response.  For this reason, exposing the `id_str` and similar fields via Twitter4J would be useful.

I can confirm that, at the time PR #259 was raised, raw Twitter response from the Filter API contained the correct id values, and these values were being parsed incorrectly by Twitter4J.  Specifically, this was under MacOS using Java 8.

I can only speculate as to the cause of this, but my suspicion is that is has to do with one of the following:
- Storing Twitter snowflake ids (64-bit unsigned) as a Java long (64-bit signed)
- The JSON parser used by Twitter4J not handling 64-bit unsigned longs correctly

**Comment by takke** [comment]
@aadawi 

I checked raw json and id and id_str values are  COMPLETELY same.

```
$ twurl /1.1/statuses/show/889303978709729280.json
{"created_at":"Mon Jul 24 01:59:25 +0000 2017","id":889303978709729280,"id_str":"889303978709729280","text":"RT @pumakorea: \uc6b0\ub9ac\uac00 \uc900\ube44\ud55c \uc791\uc740 \uc815\uc131\uc774\n\ub108\ud76c\ub97c \uc6c3\uac8c  \ud560 \uc218 \uc788\uc73c\uba74 \uc88b\uaca0\uc5b4.\n\nmade by BTS\n\nBTS \ud32c\uc0ac\uc778\ud68c \uc774\ubca4\ud2b8 \uc790\uc138\ud788 \ubcf4\uae30&gt; https:\/\/t.co\/ts2gixlojg https:\/\/t.co\/6JlD75IGf1","truncated":false, ... ,"lang":"ko"}
```
(full content is here: https://gist.github.com/takke/2636075bceb1ac7cb982c841bda12ece)

Which tool did you check (or re-format) json with?
If you use a JavaScript-based tool, the id values will be corrupted.

**Comment by aadawi** [comment]
@takke you totally right but try to read it as JSON you will see the difference.

**Comment by yusuke** [comment]
At this moment, unsigned 64 bit is wide enough to handle ids provided by the API.
When the time has come, I'll add string based ids.

**Comment by yusuke** [comment]
Close for now.

**Comment by rhuss** [comment]
> At this moment, signed 64 bit is wide enough to handle ids provided by the API.
When the time has come, I'll add string based ids.

I think the time has come. Twitter uses now ids like `1524831183200260097` which is outside of `[-(2**53)+1, (2**53)-1]` which is [the range that JavaScript can deal with](https://stackoverflow.com/questions/12254749/what-is-the-maximum-integer-allowed-in-a-javascript-variable). As the JSON output of Twitter4J can be consumed by anybody (also JavaScript and other languages that have similar limitations), adding a string variation of the id would be very friendly and helpful, otherwise this library can't be really be used in an heterogeneous context.

**Pull request closed without merging**
