### PR TITLE
Add in sitestreams handler for quoted tweets

### PR DESCRIPTION
**Pull request by miketempleman**

### CODE REVIEW

**Comment by eliasisrael** [comment]
These changes permit site streams handlers to manage quoted tweets, and add in handlers for the mute and unmute events.

**Comment by eliasisrael** [comment]
Oh, darn it. I obviously did not intend to include the pom.xml changes in this pull request. I'll repair that.

**Comment by miketempleman** [comment]
I had already requested a pull for this

From:  Eli Israel <notifications@github.com>
Reply-To:  yusuke/twitter4j
<reply+00173e9b75882af6d090ca0f4b004e536d7ad52a0780a2ae92cf00000001130539d09
2a169ce08225cd0@reply.github.com>
Date:  Saturday, March 19, 2016 at 8:01 AM
To:  yusuke/twitter4j <twitter4j@noreply.github.com>
Cc:  Michael Templeman <mike@talkingfrog.net>
Subject:  Re: [twitter4j] Add in sitestreams handler for quoted tweets
(#233)


Oh, darn it. I obviously did not intend to include the pom.xml changes in
this pull request. I'll repair that.


You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/yusuke/twitter4j/pull/233#issuecomment-198737436>

**Comment by eliasisrael** [comment]
I think it just added my stuff to the end of it.

**Comment by miketempleman** [comment]
You probably should note that you added the mute events. Otherwise he might
miss it. siteStreams users will want that.

From:  Eli Israel <notifications@github.com>
Reply-To:  yusuke/twitter4j
<reply+00173e9bc5408bcd9346dfd6e0843756cffa006a27859d2a92cf00000001130570f59
2a169ce08225cd0@reply.github.com>
Date:  Saturday, March 19, 2016 at 11:56 AM
To:  yusuke/twitter4j <twitter4j@noreply.github.com>
Cc:  Michael Templeman <mike@talkingfrog.net>
Subject:  Re: [twitter4j] Add in sitestreams handler for quoted tweets
(#233)

I think it just added my stuff to the end of it.

> On Mar 19, 2016, at 12:55 PM, Michael Templeman <notifications@github.com>
wrote:
> 
> I had already requested a pull for this
> 
> From: Eli Israel <notifications@github.com>
> Reply-To: yusuke/twitter4j
> <reply+00173e9b75882af6d090ca0f4b004e536d7ad52a0780a2ae92cf00000001130539d09
> 2a169ce08225cd0@reply.github.com>
> Date: Saturday, March 19, 2016 at 8:01 AM
> To: yusuke/twitter4j <twitter4j@noreply.github.com>
> Cc: Michael Templeman <mike@talkingfrog.net>
> Subject: Re: [twitter4j] Add in sitestreams handler for quoted tweets
> (#233)
> 
> 
> Oh, darn it. I obviously did not intend to include the pom.xml changes in
> this pull request. I'll repair that.
> 
> ?
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/yusuke/twitter4j/pull/233#issuecomment-198737436>
> 
> 
> 
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
<https://github.com/yusuke/twitter4j/pull/233#issuecomment-198777273>



—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/yusuke/twitter4j/pull/233#issuecomment-198777383>

**Comment by eliasisrael** [comment]
I put a comment in to that effect in the pull request.

**Pull request merged**
