### PR TITLE
Support 280 characters per tweet

### PR DESCRIPTION
**Pull request by tzellman**
Twitter official [documentation](https://developer.twitter.com/en/docs/developer-utilities/twitter-text.html)

### CODE REVIEW

**Comment by eos1d3** [comment]
This won't work as Twitter definitely does not count tweet as simple as just 280 length in string. Character of CJK and emojis are counted as TWO. You need a lot codes to count the real length now.

**Comment by krallus** [comment]
Counting characters regardless if they are "counted as two" is actually not that hard. One simply has to count the codepoint length of each character which Java supports in its core API.  I do this in pullrequest #263, albeit to solve a different problem.

**Comment by krallus** [comment]
In particular, take a look at these methods in the Java API:
Character.charCount
String.codePointAt
StringBuilder.appendCodePoint
and especially...
String.codePointCount

**Comment by eos1d3** [comment]
Not possible to use Character.charCount. Just had a test and find CJK character returns 1 while emoji return 2.

By testing with browser tweet box, CJK and emojis are weighted as two.

https://developer.twitter.com/en/docs/developer-utilities/twitter-text.html

```
for codepoint in text:
	Weight ← defaultWeight
	For range in ranges:
		if codepoint in range:
			weight ← range.weight
			break
	weightedLength ← weightedLength + weight

```

I have to go through each codepoint to check if they are in the unicode ranges. The list is long. I have no idea if there is simple method to find the range.weight. The tweet text library seems not yet updated too.

**Comment by ivanviragine** [comment]
Any plans on supporting this?

**Comment by wizquest-labs** [comment]
https://gist.github.com/nishemon/8618f0eb8cb78e6dcfe6217a7e7cb24b This looks like a workaround till we get the actual fix in place

**Comment by joesondow** [comment]
Twitter's rules for CJK and Emoji characters have not changed. Those characters always used different numbers of characters, even before 280 was the new maximum. The CJK/emoji issue is not directly related to the 280 max issue. I don't understand the objection to this pull request, other than the fact it appears to need some fixes to get all the unit tests working.

**Comment by time2try** [comment]
You can just add `setTweetModeExtended(true)` to your twitter4j `ConfigurationBuilder` as is explained perfectly in this blog [post](https://nmatpt.com/blog/2018/01/06/twitter4j-extended-mode/). Best and easiest to implement solution that I've found.

**Comment by eos1d3** [comment]
There is no need to use `setTweetModeExtended` to tweet more than 140 characters. Version 4.0.6 can do it without any extra setting. I have been running an application for a long time without any problem.

**Pull request merged**
