### PR TITLE
Replace non-free org.jason code

### PR DESCRIPTION
**Pull request by osamuaoki**
Replace problematic non-free org.jason code with the cleanroom
re-implitation one by the android team obtained from:

 $ git clone https://android.googlesource.com/platform/libcore

Files copied are
 json/src/main/java/org/json/JSONArray.java
 json/src/main/java/org/json/JSONException.java
 json/src/main/java/org/json/JSONObject.java
 json/src/main/java/org/json/JSONTokener.java

### CODE REVIEW

**Comment by yusuke** [comment]
great! But this PR doesn't compile.
Change the package totwitter4j, not org.json.
And ensure that the whole project compiles.

**Comment by steveblackmon** [comment]
it would be great to see this wrapped up and merged - Apache Streams depends on Twitter4J and Apache Foundation recently declared org.json:json category X.

@osamuaoki are you still interested in finishing this?  if not perhaps someone else will pick it up?

**Comment by jfrazee** [comment]
@yusuke @osamuaoki It's not just a single project at this point fwiw. There are multiple Apache projects who are halting the distribution of certain modules until this can be addressed.

**Comment by mattyb149** [comment]
Indeed, Apache NiFi is another, we've had to remove our (VERY popular) GetTwitter processor as a result

**Comment by tdunning** [comment]
I have an alternative to json.org's library at https://github.com/tdunning/open-json

The current version in maven central doesn't quite do everything that twitter4j needs. The important differences are JSONException needs to be unchecked and there are two constructors for JSONTokener that are required. I have a version of twitter4j that has these improvements in it, it compiles, but the tests don't run because of a missing resource.

How would you guys like to handle this?

**Comment by yusuke** [comment]
fixed at #254

**Pull request closed without merging**
