### PR TITLE
Replace code from json.org with Android derived code

### PR DESCRIPTION
**Pull request by tdunning**
Here is a proposed update to handle the switch from json.org code to an open source version.

### CODE REVIEW

**Comment by joewitt** [comment]
@tdunning i think the LICENSE needs to be reset back to default ASLv2 now that this PR removes the json.org code.  https://github.com/yusuke/twitter4j/blob/15ecc6a6a007af85385f0afb58300f058ac70f67/LICENSE.txt#L179

Do you agree?

**Comment by tdunning** [comment]
Joe,

Very good point.

**Comment by tdunning** [comment]
Added this change to the PR.

**Comment by yusuke** [comment]
I'm back. Thanks for the contribution.
I found a slight bug in JSON.java, but I managed to fix it. Thanks!

**Comment by yusuke** [comment]
fixed at #254

**Comment by tdunning** [comment]
@yusuke What bug did you find? Did you push a change back to my version?

**Pull request merged**
